# -*- coding: utf-8 -*-
"""크롤링 12주차(이경흔).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yij5fDdjOz5KVh6DcTNQth0dtFJUoY0K
"""

!pip install selenium

from google.colab import drive
drive.mount('/content/drive')
!pwd
!ls

!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import time

a= input('야구, 축구, 농구, 배구 중 하나를 선택하세요. : ')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
time.sleep(2)

if a=='야구':
    driver.get("https://sports.news.naver.com/kbaseball/index.nhn")
    boxes = driver.find_elements_by_css_selector("#content > div > div.home_grid > div.content > div.home_article > div.home_news > ul > li")
    print('<추천뉴스>')
    for box in boxes:
        title = box.find_element_by_css_selector("a > span").text
        print(title)

    driver.close()

elif a=='축구':
    driver.get("https://sports.news.naver.com/kfootball/index.nhn")
    boxes = driver.find_elements_by_css_selector("#content > div > div.home_grid > div.content > div.home_article > div.home_news > ul > li")
    print('<추천뉴스>')
    for box in boxes:
        title = box.find_element_by_css_selector("a > span").text
        print(title)
        
elif a=='농구':
    driver.get("https://sports.news.naver.com/basketball/index")
    boxes = driver.find_elements_by_css_selector("#content > div > div.home_grid > div.content > div.home_article > div.home_news > ul > li")
    print('<추천뉴스>')
    for box in boxes:
        title = box.find_element_by_css_selector("a > span").text
        print(title)

elif a=='배구':
    driver.get("https://sports.news.naver.com/volleyball/index")
    boxes = driver.find_elements_by_css_selector("#content > div > div.home_grid > div.content > div.home_article > div.home_news > ul > li")
    print('<추천뉴스>')
    for box in boxes:
        title = box.find_element_by_css_selector("a > span").text
        print(title)

    driver.close()
